-- HOW MANY TRIPS OCCURE PER HOUR?
SELECT  
    DATEPART(HOUR, PICKUP_DATETIME) AS PICKUP_HOUR,
    COUNT(*) AS TOTAL_TRIPS
    FROM STAGE.NYC_TAXI
    GROUP BY DATEPART(HOUR, PICKUP_DATETIME)
    ORDER BY PICKUP_HOUR;

-- DETERMININING HOW MANY TRIPS OCCURE A DAY?

SELECT 
    CAST(PICKUP_DATETIME AS DATE) AS TRIP_DATE,
    COUNT(*) AS TOTAL_TRIP
FROM 
    STAGE.NYC_TAXI 
GROUP BY CAST(PICKUP_DATETIME AS DATE)
ORDER BY TRIP_DATE;

-- DETEMINING HOW MANY TRIPS OCCURE A WEEK.
SELECT * FROM STAGE.NYC_TAXI;
SELECT 
    DATEPART(WEEK, PICKUP_DATETIME) AS TRIP_BY_WEEK,
    COUNT(*) AS TOTAL_TRIP
FROM STAGE.NYC_TAXI
GROUP BY  DATEPART(WEEK, PICKUP_DATETIME)
ORDER BY TRIP_BY_WEEK;

-- DETEMINING HOW MANY TRIPS A MOUNTH.
SELECT 
    DATEPART(MONTH, PICKUP_DATETIME) AS TRIP_BY_MONTH,
    COUNT(*) AS TOTAL_TRIP_A_MONTH
FROM STAGE.NYC_TAXI 
GROUP BY DATEPART(MONTH, PICKUP_DATETIME)
ORDER BY TRIP_BY_MONTH; 

-- DETERMINING THE BUSIEST DAYS
SELECT 
    CAST(PICKUP_DATETIME AS DATE) AS PICKUP_DATE,
    DATENAME(WEEKDAY, CAST(PICKUP_DATETIME AS DATE)) AS DAY_OF_THE_WEEK,
    COUNT(*) AS TRIP_COUNT
FROM STAGE.NYC_TAXI
GROUP BY CAST(PICKUP_DATETIME AS DATE)
ORDER BY TRIP_COUNT DESC;

